// <auto-generated />
using System;
using DoAnV2.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnV2.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260809111828_SyncShipmentEntityFromSnapshot")]
    partial class SyncShipmentEntityFromSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnV2.Domain.Entities.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("batch_code");

                    b.Property<string>("BlockchainBatchId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("blockchain_batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_stage");

                    b.Property<string>("DataHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_hash");

                    b.Property<double>("ExpectedQuantity")
                        .HasColumnType("float")
                        .HasColumnName("expected_quantity");

                    b.Property<Guid>("FarmAreaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("farm_area_id");

                    b.Property<Guid?>("FarmAreaId2")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("farm_area_id2");

                    b.Property<Guid>("FruitTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fruit_type_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MetadataURI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_uri");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("planting_date");

                    b.Property<Guid>("ProcessorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("processor_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("RepresentativeWorkerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("representative_worker_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_batches");

                    b.HasIndex("BatchCode")
                        .IsUnique()
                        .HasDatabaseName("ix_batches_batch_code");

                    b.HasIndex("FarmAreaId")
                        .HasDatabaseName("ix_batches_farm_area_id");

                    b.HasIndex("FarmAreaId2")
                        .HasDatabaseName("ix_batches_farm_area_id2");

                    b.HasIndex("FruitTypeId")
                        .HasDatabaseName("ix_batches_fruit_type_id");

                    b.HasIndex("ProcessorId")
                        .HasDatabaseName("ix_batches_processor_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_batches_product_id");

                    b.HasIndex("RepresentativeWorkerId")
                        .HasDatabaseName("ix_batches_representative_worker_id");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.BatchWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_date");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("bit")
                        .HasColumnName("is_representative");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_batch_workers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_batch_workers_user_id");

                    b.HasIndex("BatchId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_batch_workers_batch_id_user_id");

                    b.ToTable("batch_workers", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.BlockchainTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<long?>("BlockNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("block_number");

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("function_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubBatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sub_batch_id");

                    b.Property<Guid?>("SubBatchId2")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sub_batch_id2");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("transaction_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("wallet_address");

                    b.HasKey("Id")
                        .HasName("pk_blockchain_transactions");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_blockchain_transactions_batch_id");

                    b.HasIndex("SubBatchId")
                        .HasDatabaseName("ix_blockchain_transactions_sub_batch_id");

                    b.HasIndex("SubBatchId2")
                        .HasDatabaseName("ix_blockchain_transactions_sub_batch_id2");

                    b.HasIndex("TransactionHash")
                        .IsUnique()
                        .HasDatabaseName("ix_blockchain_transactions_transaction_hash");

                    b.ToTable("blockchain_transactions", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.CultivationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activity_type");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrlsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_urls_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("log_date");

                    b.Property<string>("MetadataURI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_uri");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_cultivation_logs");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_cultivation_logs_batch_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_cultivation_logs_user_id");

                    b.ToTable("cultivation_logs", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.FarmArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<double>("Area")
                        .HasColumnType("float")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("district");

                    b.Property<string>("GPS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gps");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("owner_name");

                    b.Property<string>("PlantingCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("planting_code");

                    b.Property<Guid>("ProcessorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("processor_id");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province");

                    b.Property<string>("SoilType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("soil_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ward");

                    b.HasKey("Id")
                        .HasName("pk_farm_areas");

                    b.HasIndex("ProcessorId")
                        .HasDatabaseName("ix_farm_areas_processor_id");

                    b.ToTable("farm_areas", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.FruitType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProcessorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("processor_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fruit_types");

                    b.HasIndex("ProcessorId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_fruit_types_processor_id_code");

                    b.ToTable("fruit_types", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Harvest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DataHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_hash");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("harvest_date");

                    b.Property<string>("InitialQuality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("initial_quality");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MetadataURI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_uri");

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RepresentativeUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("representative_user_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_harvests");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_harvests_batch_id");

                    b.HasIndex("RepresentativeUserId")
                        .HasDatabaseName("ix_harvests_representative_user_id");

                    b.ToTable("harvests", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("asset_type");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("document_name");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("document_number");

                    b.Property<string>("FileURI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_uri");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("inspection_date");

                    b.Property<string>("InspectionUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("inspection_unit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result");

                    b.Property<Guid?>("SubBatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sub_batch_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inspections");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_inspections_batch_id");

                    b.HasIndex("SubBatchId")
                        .HasDatabaseName("ix_inspections_sub_batch_id");

                    b.ToTable("inspections", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.InventoryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MaterialItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("material_item_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_logs");

                    b.HasIndex("MaterialItemId")
                        .HasDatabaseName("ix_inventory_logs_material_item_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_inventory_logs_user_id");

                    b.ToTable("inventory_logs", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.MaterialItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("code");

                    b.Property<double?>("Concentration")
                        .HasColumnType("float")
                        .HasColumnName("concentration");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<double?>("DosagePerHa")
                        .HasColumnType("float")
                        .HasColumnName("dosage_per_ha");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_type");

                    b.Property<string>("NPKRatio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("npk_ratio");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProcessorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("processor_id");

                    b.Property<double>("QuantityInStock")
                        .HasColumnType("float")
                        .HasColumnName("quantity_in_stock");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supplier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_material_items");

                    b.HasIndex("ProcessorId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_material_items_processor_id_code");

                    b.ToTable("material_items", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Packaging", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("asset_type");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrlsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_urls_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<DateTime>("PackDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("pack_date");

                    b.Property<string>("Smell")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("smell");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("specification");

                    b.Property<string>("Standard")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("standard");

                    b.Property<string>("StorageGuide")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("storage_guide");

                    b.Property<Guid?>("SubBatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sub_batch_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsageGuide")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usage_guide");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_packagings");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_packagings_batch_id");

                    b.HasIndex("SubBatchId")
                        .HasDatabaseName("ix_packagings_sub_batch_id");

                    b.ToTable("packagings", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("process_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stage");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("step_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_process_steps");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_process_steps_process_id");

                    b.ToTable("process_steps", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Processing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DataHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_hash");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("ImageUrlsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_urls_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MetadataURI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_uri");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("process_type");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_processings");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_processings_batch_id");

                    b.ToTable("processings", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("FruitTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fruit_type_id");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_type");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("short_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variety")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("variety");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("FruitTypeId")
                        .HasDatabaseName("ix_products_fruit_type_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.ProductionProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProcessorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("processor_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_production_processes");

                    b.HasIndex("ProcessorId")
                        .HasDatabaseName("ix_production_processes_processor_id");

                    b.ToTable("production_processes", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.QRCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("QRValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("qr_value");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_qr_codes");

                    b.ToTable("qr_codes", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 9, 11, 18, 26, 489, DateTimeKind.Utc).AddTicks(236),
                            Description = "Quản trị hệ thống",
                            IsDeleted = false,
                            RoleName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 9, 11, 18, 26, 489, DateTimeKind.Utc).AddTicks(2104),
                            Description = "Nông dân / Công nhân",
                            IsDeleted = false,
                            RoleName = "FARMER"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 9, 11, 18, 26, 489, DateTimeKind.Utc).AddTicks(2110),
                            Description = "Hợp tác xã / Doanh nghiệp",
                            IsDeleted = false,
                            RoleName = "PROCESSOR"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 8, 9, 11, 18, 26, 489, DateTimeKind.Utc).AddTicks(2113),
                            Description = "Cửa hàng bán lẻ",
                            IsDeleted = false,
                            RoleName = "RETAILER"
                        });
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("asset_type");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("batch_id");

                    b.Property<string>("CarrierInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("carrier_info");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DataHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_hash");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("destination");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expected_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MetadataURI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_uri");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pickup_location");

                    b.Property<string>("ReadyDataHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ready_data_hash");

                    b.Property<DateTime?>("ReadyForSaleDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ready_for_sale_date");

                    b.Property<string>("ReadyMetadataURI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ready_metadata_uri");

                    b.Property<string>("ReadyTransactionHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ready_transaction_hash");

                    b.Property<string>("ReceiveDataHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receive_data_hash");

                    b.Property<string>("ReceiveMetadataURI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receive_metadata_uri");

                    b.Property<string>("ReceiveTransactionHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receive_transaction_hash");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("received_date");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("retailer_id");

                    b.Property<string>("ShipTransactionHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ship_transaction_hash");

                    b.Property<string>("ShippingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shipping_code");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("shipping_date");

                    b.Property<Guid?>("SubBatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sub_batch_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_shipments");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_shipments_batch_id");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("ix_shipments_retailer_id");

                    b.HasIndex("SubBatchId")
                        .HasDatabaseName("ix_shipments_sub_batch_id");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.SubBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_stage");

                    b.Property<string>("DataHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_hash");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MetadataURI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_uri");

                    b.Property<string>("PackageCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("package_code");

                    b.Property<Guid>("ParentBatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_batch_id");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("qr_code");

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("quantity");

                    b.Property<string>("SubBatchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("sub_batch_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sub_batches");

                    b.HasIndex("ParentBatchId")
                        .HasDatabaseName("ix_sub_batches_parent_batch_id");

                    b.HasIndex("SubBatchCode")
                        .IsUnique()
                        .HasDatabaseName("ix_sub_batches_sub_batch_code");

                    b.ToTable("sub_batches", (string)null);
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("EncryptedPrivateKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("encrypted_private_key");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("WalletAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("wallet_address");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 9, 11, 18, 27, 176, DateTimeKind.Utc).AddTicks(4525),
                            Email = "admin@gmail.com",
                            FullName = "System Administrator",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$VSKjT1g.fZCbhdFLRj555.WDfeFM.QuOwb7lIQzN5sjGLL/aVJK8u",
                            Phone = "0000000000",
                            RoleId = 1,
                            Status = "APPROVED"
                        });
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Batch", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.FarmArea", "FarmArea")
                        .WithMany()
                        .HasForeignKey("FarmAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batches_farm_areas_farm_area_id");

                    b.HasOne("DoAnV2.Domain.Entities.FarmArea", null)
                        .WithMany("Batches")
                        .HasForeignKey("FarmAreaId2")
                        .HasConstraintName("fk_batches_farm_areas_farm_area_id2");

                    b.HasOne("DoAnV2.Domain.Entities.FruitType", "FruitType")
                        .WithMany()
                        .HasForeignKey("FruitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batches_fruit_types_fruit_type_id");

                    b.HasOne("DoAnV2.Domain.Entities.User", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batches_users_processor_id");

                    b.HasOne("DoAnV2.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batches_products_product_id");

                    b.HasOne("DoAnV2.Domain.Entities.User", "RepresentativeWorker")
                        .WithMany("RepresentedBatches")
                        .HasForeignKey("RepresentativeWorkerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_batches_users_representative_worker_id");

                    b.Navigation("FarmArea");

                    b.Navigation("FruitType");

                    b.Navigation("Processor");

                    b.Navigation("Product");

                    b.Navigation("RepresentativeWorker");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.BatchWorker", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.Batch", "Batch")
                        .WithMany("BatchWorkers")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_batch_workers_batches_batch_id");

                    b.HasOne("DoAnV2.Domain.Entities.User", "User")
                        .WithMany("BatchWorkers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_batch_workers_users_user_id");

                    b.Navigation("Batch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.BlockchainTransaction", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.Batch", "Batch")
                        .WithMany("BlockchainTransactions")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("fk_blockchain_transactions_batches_batch_id");

                    b.HasOne("DoAnV2.Domain.Entities.SubBatch", "SubBatch")
                        .WithMany()
                        .HasForeignKey("SubBatchId")
                        .HasConstraintName("fk_blockchain_transactions_sub_batches_sub_batch_id");

                    b.HasOne("DoAnV2.Domain.Entities.SubBatch", null)
                        .WithMany("BlockchainTransactions")
                        .HasForeignKey("SubBatchId2")
                        .HasConstraintName("fk_blockchain_transactions_sub_batches_sub_batch_id2");

                    b.Navigation("Batch");

                    b.Navigation("SubBatch");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.CultivationLog", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.Batch", "Batch")
                        .WithMany("CultivationLogs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cultivation_logs_batches_batch_id");

                    b.HasOne("DoAnV2.Domain.Entities.User", "User")
                        .WithMany("CultivationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cultivation_logs_users_user_id");

                    b.Navigation("Batch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.FarmArea", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.User", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_farm_areas_users_processor_id");

                    b.Navigation("Processor");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.FruitType", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.User", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fruit_types_users_processor_id");

                    b.Navigation("Processor");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Harvest", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.Batch", "Batch")
                        .WithMany("Harvests")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_harvests_batches_batch_id");

                    b.HasOne("DoAnV2.Domain.Entities.User", "RepresentativeUser")
                        .WithMany("Harvests")
                        .HasForeignKey("RepresentativeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_harvests_users_representative_user_id");

                    b.Navigation("Batch");

                    b.Navigation("RepresentativeUser");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Inspection", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.Batch", "Batch")
                        .WithMany("Inspections")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("fk_inspections_batches_batch_id");

                    b.HasOne("DoAnV2.Domain.Entities.SubBatch", "SubBatch")
                        .WithMany("Inspections")
                        .HasForeignKey("SubBatchId")
                        .HasConstraintName("fk_inspections_sub_batches_sub_batch_id");

                    b.Navigation("Batch");

                    b.Navigation("SubBatch");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.InventoryLog", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.MaterialItem", "MaterialItem")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("MaterialItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_logs_material_items_material_item_id");

                    b.HasOne("DoAnV2.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_logs_users_user_id");

                    b.Navigation("MaterialItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.MaterialItem", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.User", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_material_items_users_processor_id");

                    b.Navigation("Processor");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Packaging", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.Batch", "Batch")
                        .WithMany("Packagings")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("fk_packagings_batches_batch_id");

                    b.HasOne("DoAnV2.Domain.Entities.SubBatch", "SubBatch")
                        .WithMany("Packagings")
                        .HasForeignKey("SubBatchId")
                        .HasConstraintName("fk_packagings_sub_batches_sub_batch_id");

                    b.Navigation("Batch");

                    b.Navigation("SubBatch");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.ProcessStep", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.ProductionProcess", "Process")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_steps_production_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Processing", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.Batch", "Batch")
                        .WithMany("Processings")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processings_batches_batch_id");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Product", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.FruitType", "FruitType")
                        .WithMany("Products")
                        .HasForeignKey("FruitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_fruit_types_fruit_type_id");

                    b.Navigation("FruitType");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.ProductionProcess", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.User", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_processes_users_processor_id");

                    b.Navigation("Processor");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.Batch", "Batch")
                        .WithMany("Shipments")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("fk_shipments_batches_batch_id");

                    b.HasOne("DoAnV2.Domain.Entities.User", "Retailer")
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipments_users_retailer_id");

                    b.HasOne("DoAnV2.Domain.Entities.SubBatch", "SubBatch")
                        .WithMany("Shipments")
                        .HasForeignKey("SubBatchId")
                        .HasConstraintName("fk_shipments_sub_batches_sub_batch_id");

                    b.Navigation("Batch");

                    b.Navigation("Retailer");

                    b.Navigation("SubBatch");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.SubBatch", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.Batch", "ParentBatch")
                        .WithMany("SubBatches")
                        .HasForeignKey("ParentBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sub_batches_batches_parent_batch_id");

                    b.Navigation("ParentBatch");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.User", b =>
                {
                    b.HasOne("DoAnV2.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Batch", b =>
                {
                    b.Navigation("BatchWorkers");

                    b.Navigation("BlockchainTransactions");

                    b.Navigation("CultivationLogs");

                    b.Navigation("Harvests");

                    b.Navigation("Inspections");

                    b.Navigation("Packagings");

                    b.Navigation("Processings");

                    b.Navigation("Shipments");

                    b.Navigation("SubBatches");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.FarmArea", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.FruitType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.MaterialItem", b =>
                {
                    b.Navigation("InventoryLogs");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.ProductionProcess", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.SubBatch", b =>
                {
                    b.Navigation("BlockchainTransactions");

                    b.Navigation("Inspections");

                    b.Navigation("Packagings");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("DoAnV2.Domain.Entities.User", b =>
                {
                    b.Navigation("BatchWorkers");

                    b.Navigation("CultivationLogs");

                    b.Navigation("Harvests");

                    b.Navigation("RepresentedBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
